version: "3"
services:
  # redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - "REDIS_PASSWORD=redis"
      - "REDIS_USER=user"
      - "REDIS_USER_PASSWORD=password"

# отвечает за сохранение данных в память компа из докера
#    volumes:
#      - ./redisdata:/data
# задает лимиты на потребление ресурсов
#    deploy:
#      resources:
#        limits:
#          cpus: '0.50'
#          memory: 512M
#        reservations:
#          cpus: '0.25'
#          memory: 256M
  # приложуха что бы смотреть состояние redis
  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - "5540:5540"
#    environment:
#      REDIS_USER: redis
#      REDIS_PASSWORD: redis
#      REDIS_PORT: 6379